FROM python:3-slim-buster

# install deps for gcc on pip
RUN apt-get -y update && apt-get install -y --no-install-recommends \
	gcc \
	python-dev \
	&& apt-get clean && apt-get autoremove && rm -rf /var/lib/apt/lists/*

COPY . /project
WORKDIR /project

RUN pip3 install -r requirements.txt

EXPOSE 5001

ENTRYPOINT [ "python", "main.py" ]
