version: '3.7'
services:
  system-info:
    image: torizonextras/pasta-demo-system-info:latest-x86
    ports:
      - "5001:5001"
    volumes:
      - type: bind
        source: /sys
        target: /sys
        read_only: true
    privileged: true
