version: '3.7'
services:
  system-control:
    image: torizonextras/pasta-demo-system-control:latest-arm32v7
    ports:
      - "5002:5002"
    volumes:
      - type: bind
        source: /sys/class/pwm
        target: /sys/class/pwm